name: PR Tests

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt,clippy
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  format:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        components: rustfmt
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Run rustfmt --check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        components: rustfmt
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        components: rustfmt
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Test
      run: make test-ci

  check-typos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check spelling
      uses: crate-ci/typos@v1.13.23
